import random

from locust import HttpUser, between, task


class LoadTestUser(HttpUser):
    wait_time = between(1, 5)

    keywords = [
        {"name": "sữa", "id": 0},
        {"name": "trà", "id": 1},
        {"name": "cà phê", "id": 2},
        {"name": "nước ngọt", "id": 3},
        {"name": "bánh mì", "id": 4},
        {"name": "kẹo", "id": 5},
        {"name": "sữa chua", "id": 6},
        {"name": "bia", "id": 7},
        {"name": "mì gói", "id": 8},
        {"name": "gạo", "id": 9},
        {"name": "dầu ăn", "id": 10},
        {"name": "nước mắm", "id": 11},
        {"name": "đường", "id": 12},
        {"name": "muối", "id": 13},
        {"name": "bột ngọt", "id": 14},
        {"name": "sữa bột", "id": 15},
        {"name": "bỉm", "id": 16},
        {"name": "khăn giấy", "id": 17},
        {"name": "nước rửa chén", "id": 18},
        {"name": "xà phòng", "id": 19},
        {"name": "kem đánh răng", "id": 20},
        {"name": "dầu gội", "id": 21},
        {"name": "sữa tắm", "id": 22},
        {"name": "nước xả vải", "id": 23},
        {"name": "bột giặt", "id": 24},
        {"name": "nước lau sàn", "id": 25},
        {"name": "tã giấy", "id": 26},
        {"name": "khăn ướt", "id": 27},
        {"name": "bàn chải", "id": 28},
        {"name": "thực phẩm chức năng", "id": 29},
        {"name": "vitamin", "id": 30},
        {"name": "mật ong", "id": 31},
        {"name": "nước ép", "id": 32},
        {"name": "trái cây", "id": 33},
        {"name": "rau củ", "id": 34},
        {"name": "thịt heo", "id": 35},
        {"name": "thịt gà", "id": 36},
        {"name": "cá", "id": 37},
        {"name": "tôm", "id": 38},
        {"name": "mực", "id": 39},
        {"name": "bánh kẹo", "id": 40},
        {"name": "snack", "id": 41},
        {"name": "bánh quy", "id": 42},
        {"name": "chocolate", "id": 43},
        {"name": "kẹo mút", "id": 44},
        {"name": "nước khoáng", "id": 45},
        {"name": "sữa tươi", "id": 46},
        {"name": "phô mai", "id": 47},
        {"name": "bơ", "id": 48},
        {"name": "kem", "id": 49},
        {"name": "yogurt", "id": 50},
        {"name": "nước tăng lực", "id": 51},
        {"name": "trà xanh", "id": 52},
        {"name": "cà phê sữa", "id": 53},
        {"name": "nước dừa", "id": 54},
        {"name": "sữa đậu nành", "id": 55},
        {"name": "bánh trung thu", "id": 56},
        {"name": "mứt", "id": 57},
        {"name": "hạt điều", "id": 58},
        {"name": "hạt dẻ", "id": 59},
        {"name": "ô mai", "id": 60},
        {"name": "nước tương", "id": 61},
        {"name": "tương ớt", "id": 62},
        {"name": "mayonnaise", "id": 63},
        {"name": "dầu hào", "id": 64},
        {"name": "gia vị", "id": 65},
        {"name": "bột chiên giòn", "id": 66},
        {"name": "bột nêm", "id": 67},
        {"name": "thịt bò", "id": 68},
        {"name": "trứng gà", "id": 69},
        {"name": "trứng vịt", "id": 70},
        {"name": "đậu hũ", "id": 71},
        {"name": "chả lụa", "id": 72},
        {"name": "xúc xích", "id": 73},
        {"name": "thịt nguội", "id": 74},
        {"name": "cá hộp", "id": 75},
        {"name": "thịt hộp", "id": 76},
        {"name": "mì Ý", "id": 77},
        {"name": "bún", "id": 78},
        {"name": "phở", "id": 79},
        {"name": "bánh canh", "id": 80},
        {"name": "nước lọc", "id": 81},
        {"name": "khăn mặt", "id": 82},
        {"name": "dép", "id": 83},
        {"name": "quần áo trẻ em", "id": 84},
        {"name": "đồ chơi", "id": 85},
        {"name": "sách", "id": 86},
        {"name": "vở", "id": 87},
        {"name": "bút", "id": 88},
        {"name": "hộp đựng thức ăn", "id": 89},
        {"name": "ly nhựa", "id": 90},
        {"name": "muỗng", "id": 91},
        {"name": "đĩa", "id": 92},
        {"name": "chén", "id": 93},
        {"name": "nồi", "id": 94},
        {"name": "chảo", "id": 95},
        {"name": "bếp ga", "id": 96},
        {"name": "bình nước", "id": 97},
        {"name": "hộp cơm", "id": 98},
        {"name": "túi đựng rác", "id": 99}
    ]

    @task
    def search(self):
        keyword = random.choice(self.keywords)["name"]

        self.client.post(
            url="/api/product-search/search_text",
            headers={
                "Accept": "*/*",
                "Authorization": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Il9HSDZrYllkZ3RxZDdLNHNrUW1uSGI4dUh6OCIsImtpZCI6Il9HSDZrYllkZ3RxZDdLNHNrUW1uSGI4dUh6OCJ9.eyJpc3MiOiJjb25jdW5nLmNvbSIsImF1ZCI6ImNvbmN1bmcuY29tL3Jlc291cmNlcyIsImV4cCI6MTc0MjYyOTk1NCwibmJmIjoxNzQyNjI2MzU0LCJjbGllbnRfaWQiOiJDQ0kuU3dhZ2dlci5DbGllbnRDcmVkZW50aWFsIiwic2NvcGUiOiJDQ0kuU3dhZ2dlciIsInN1YiI6IjE3NDIiLCJhdXRoX3RpbWUiOjE3NDI2MDM0NDUsImlkcCI6Imlkc3J2IiwiL1VzZXJJRCI6IjE3NDIiLCIvVXNlcm5hbWUiOiIyNzQxIiwiL0F2YXRhciI6ImF2YS8yMDI0MDkwOS9jZmRiMDVjZi0xMGFjLTQzMmMtODViMC1jNTIxYmI0MzgxMTQucG5nIiwiL1VzZXJUeXBlSUQiOiIxIiwiL1N1cHBsaWVySUQiOiIwIiwiL0Z1bGxuYW1lIjoiTMOqIEjhu5MgSGnhur91IEdpYW5nIiwiL0RlcGFydG1lbnRJRCI6IjI0NyIsIi9Qb3NpdGlvbklEIjoiMTI3IiwiL1N0b3JlSUQiOiI0NDEiLCIvR2VuZGVyIjoiMiIsIi9FbXBsb3llZUlEIjoiMTc0MSIsIi9WUE5Vc2VybmFtZSI6IjIwOTciLCIvVlBOUGFzc3dvcmQiOiJLdWFqWEM5eWJ6IiwiL1JvbGVJRHMiOiJbMzE1MywzMTk0LDMxNzYsMzI4MSwzMjIxLDMzMDksMzMwMSwzMzI4LDM0MDEsMzQyMywzNDQxLDM0NTEsMzQxNCwzMTc1LDMyNDUsMzQ4NywzMTQ3XSIsImFtciI6WyJwYXNzd29yZCJdfQ.X0kVpqreImlyYydvvoQB1ViNrF8jMVhgZ4AiozXLfIpc9XslU3UKSMYrvcylYMw8-j3InH13PF2ow7sh9IgNqJIFEMu8wXUS8F_NGa0wiloi_AUmuECD-gLXkT3mJn6EYI496A2OnEjMPWCC4Rv0NIRS9hkcFDhJCvNQ8uIQHO9xS7V1N3_If6JUTTHOhVPzJXfPhwGm-YD5a-aeJvqL4Qf_NwYVUbGoYXoxXKxR0Awujux7HrTB11OsaNchD8WmGDY-XhFQwi3Vq1ozIkURD0rOESqaiTIXbAQ7ZMJBes0QO8OWOo8JeMIP-Q9U8xV8RKmmTDdQXjKPFND9wg5_wg",
                "Content-Type": "application/json-patch+json"
            },
            json={
                "q": keyword,
                "filter_by": "",
                "sort_by": "",
                "facet_by": "",
                "page_index": 1,
                "page_size": 10,
                "district_id": 0,
                "include_fields": "",
                "is_search_for_ecom5": False,
                "is_return_filter": True
            }
        )
